import { StyleSheet, Platform } from 'react-native';

const createStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  titleContainer: {
    backgroundColor: theme.primary,
    paddingVertical: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  titleText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  currentDateTime: {
    marginTop: 5,
    fontSize: 16,
    color: theme.background,
  },
  taskList: {
    paddingHorizontal: 20,
    paddingBottom: 80,
  },
  taskItem: {
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: theme.primary,
    marginTop: 20,
  },
  taskTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.primary,
  },
  taskDescription: {
    fontSize: 16,
    color: theme.text,
    marginTop: 5,
  },
  taskDueDate: {
    fontSize: 14,
    color: theme.text,
    marginTop: 5,
  },
  taskStatus: {
    fontSize: 14,
    color: theme.text,
    marginTop: 5,
  },
  taskRecurring: {
    fontSize: 14,
    color: theme.text,
    marginTop: 5,
  },
  button: {
    marginTop: 10,
    padding: 10,
    backgroundColor: theme.primary,
    borderRadius: 50,
    width: '25%',
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
  },
  customButton: {
    backgroundColor: theme.primary,
    padding: 10,
    borderRadius: 5,
    marginVertical: 5,
    width: '100%',
  },
  addButton: {
    position: 'absolute',
    right: 20,
    bottom: Platform.OS === 'ios' ? 30 : 20,
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.primary,
    borderRadius: 30,
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  addButtonImage: {
    width: 30,
    height: 30,
    tintColor: '#FFFFFF',
  },
  modalView: {
    padding: 20,
    backgroundColor: theme.background,
    flexGrow: 1,
    alignItems: 'center',
    marginTop: 50,
  },
  input: {
    width: '100%',
    height: 50,
    borderColor: theme.primary,
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 10,
    fontSize: 16,
    color: theme.text,
  },
  picker: {
    width: '100%',
    height: 100,
    marginBottom: 100,
    color: theme.text,
  },
  list_calendar: {
    backgroundColor: theme.primary,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 10,
    padding: 10,
  },
  selectedDateContainer: {
    padding: 10,
    backgroundColor: theme.background,
  },
  selectedDateText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.text,
  },
  noTasksText: {
    padding: 20,
    textAlign: 'center',
    fontSize: 16,
    color: theme.text,
  },
  options: {
    color: theme.background,
    fontWeight: 'bold',
    backgroundColor: theme.primary,
    padding: 10,
    marginVertical: 10,
  },
  iconButton: {
    padding: 5,
    borderRadius: 5,
    borderWidth: 1,
    backgroundColor: theme.primary,
  },
  iconImage: {
    width: 24,
    height: 24,
    tintColor: '#FFFFFF',
  },
});

export default createStyles;